//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using LeoTools.Extension;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类ActiveManages。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class ActiveManagesBussiness
    {
        public static bool DeleteActiveManages(Expression<Func<ActiveManagesModel, bool>> expression)
        {
            return ActiveManagesDAL.dal.DeleteActiveManages(expression);
        }

        public static bool DeleteActiveManages(int id)
        {
            return ActiveManagesDAL.dal.DeleteActiveManages(m => m.ID == id);
        }

        public static ActiveManagesModel GetActiveManagesModel(Expression<Func<ActiveManagesModel, bool>> expression)
        {
            return ActiveManagesDAL.dal.GetActiveManagesModel(expression);
        }

        public static ActiveManagesModel GetActiveManagesModel(int id)
        {
            return ActiveManagesDAL.dal.GetActiveManagesModel(m => m.ID == id);
        }

        public static List<ActiveManagesModel> GetActiveManagesModels(Expression<Func<ActiveManagesModel, bool>> expression)
        {
            return ActiveManagesDAL.dal.GetActiveManagesModels(expression);
        }

        public static List<ActiveManagesModel> GetListByActiveID(int eid)
        {
            return ActiveManagesDAL.dal.GetListByActiveID(eid);
        }

        public static List<ActiveManagesModel> GetList(int type, int userid, PageFliter pageFliter)
        {
            return ActiveManagesDAL.dal.GetList(type, userid, pageFliter);
        }

        public static bool InsertActiveModel(ActiveManagesModel entity)
        {
            return ActiveManagesDAL.dal.InsertActiveModel(entity);
        }

        public static bool InsertActiveModel(List<ActiveManagesModel> entities)
        {
            return ActiveManagesDAL.dal.InsertActiveModel(entities);
        }

        public static bool UpdateActiveModel(ActiveManagesModel entity)
        {
            return ActiveManagesDAL.dal.UpdateActiveModel(entity);
        }

        public static bool UpdateActiveModel(Dictionary<Field, object> fields, Expression<Func<ActiveManagesModel, bool>> expression)
        {
            return ActiveManagesDAL.dal.UpdateActiveModel(fields, expression);
        }

        public static bool AddAdmin(ActiveManagesModel ActiveManagesModel, ActivesManageApplyModel activesManageApplyModel)
        {
            return ActiveManagesDAL.dal.AddAdmin(ActiveManagesModel, activesManageApplyModel);
        }
    }
}