//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using LeoTools.Extension;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类Actives。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class ActivesBussiness
    {
        public static bool DeleteActive(Expression<Func<ActivesModel, bool>> expression)
        {
            return ActivesDAL.dal.DeleteActive(expression);
        }

        public static bool DeleteActive(int id)
        {
            return ActivesDAL.dal.DeleteActive(m => m.ID == id);
        }

        public static ActivesModel GetActivesModel(Expression<Func<ActivesModel, bool>> expression)
        {
            return ActivesDAL.dal.GetActivesModel(expression);
        }

        public static ActivesModel GetActivesModel(int id)
        {
            return ActivesDAL.dal.GetActivesModel(m => m.ID == id);
        }

        public static List<ActivesModel> GetActivesModels(Expression<Func<ActivesModel, bool>> expression)
        {
            return ActivesDAL.dal.GetActivesModels(expression);
        }

        public static List<ActivesModel> GetList(int type, int userid, PageFliter pageFliter)
        {
            return ActivesDAL.dal.GetList(type, userid, pageFliter);
        }

        public static bool InsertActiveModel(ActivesModel entity)
        {
            return ActivesDAL.dal.InsertActiveModel(entity);
        }

        public static bool InsertActiveModel(List<ActivesModel> entities)
        {
            return ActivesDAL.dal.InsertActiveModel(entities);
        }

        public static bool UpdateActiveModel(ActivesModel entity)
        {
            return ActivesDAL.dal.UpdateActiveModel(entity);
        }

        public static bool UpdateActiveModel(Dictionary<Field, object> fields, Expression<Func<ActivesModel, bool>> expression)
        {
            return ActivesDAL.dal.UpdateActiveModel(fields, expression);
        }

        public static bool InserActiveByTran(ActivesModel signInRecordModel, List<CustomFieldModel> customFieldModels)
        {
            return ActivesDAL.dal.InserActiveByTran(signInRecordModel, customFieldModels);
        }

        public static bool UpdateActiveByTran(ActivesModel activesModel, List<CustomFieldModel> customFieldModels)
        {
            return ActivesDAL.dal.UpdateActiveByTran(activesModel, customFieldModels);
        }
    }
}