//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using LeoTools.Extension;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类AuditLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class AuditLogBussiness
    {
        public static bool DeleteAuditLog(Expression<Func<AuditLogModel, bool>> expression)
        {
            return AuditLogDAL.dal.DeleteAuditLog(expression);
        }

        public static bool DeleteAuditLog(int id)
        {
            return AuditLogDAL.dal.DeleteAuditLog(m => m.ID == id);
        }

        public static AuditLogModel GetAuditLogModel(Expression<Func<AuditLogModel, bool>> expression)
        {
            return AuditLogDAL.dal.GetAuditLogModel(expression);
        }

        public static AuditLogModel GetAuditLogModel(int id)
        {
            return AuditLogDAL.dal.GetAuditLogModel(m => m.ID == id);
        }

        public static List<AuditLogModel> GetAuditLogModels(Expression<Func<AuditLogModel, bool>> expression)
        {
            return AuditLogDAL.dal.GetAuditLogModels(expression);
        }

        public static List<AuditLogModel> GetListByActiveID(int eid)
        {
            return AuditLogDAL.dal.GetListByActiveID(eid);
        }

        public static List<AuditLogModel> GetList(int type, int userid, PageFliter pageFliter)
        {
            return AuditLogDAL.dal.GetList(type, userid, pageFliter);
        }

        public static bool InsertActiveModel(AuditLogModel entity)
        {
            return AuditLogDAL.dal.InsertActiveModel(entity);
        }

        public static bool InsertActiveModel(List<AuditLogModel> entities)
        {
            return AuditLogDAL.dal.InsertActiveModel(entities);
        }

        public static bool UpdateActiveModel(AuditLogModel entity)
        {
            return AuditLogDAL.dal.UpdateActiveModel(entity);
        }

        public static bool UpdateActiveModel(Dictionary<Field, object> fields, Expression<Func<AuditLogModel, bool>> expression)
        {
            return AuditLogDAL.dal.UpdateActiveModel(fields, expression);
        }

        public static bool AddAdmin(AuditLogModel AuditLogModel, ActivesManageApplyModel activesManageApplyModel)
        {
            return AuditLogDAL.dal.AddAdmin(AuditLogModel, activesManageApplyModel);
        }
    }
}