//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类CustomFieldValue。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class CustomFieldValueBussiness
    {
        public static bool DeleteCustomFieldValue(Expression<Func<CustomFieldValueModel, bool>> expression)
        {
            return CustomFieldValueDAL.dal.DeleteCustomFieldValue(expression);
        }

        public static bool DeleteCustomFieldValue(int id)
        {
            return CustomFieldValueDAL.dal.DeleteCustomFieldValue(m => m.ID == id);
        }

        public static CustomFieldValueModel GetCustomFieldValueModel(Expression<Func<CustomFieldValueModel, bool>> expression)
        {
            return CustomFieldValueDAL.dal.GetCustomFieldValueModel(expression);
        }

        public static CustomFieldValueModel GetCustomFieldValueModel(int id)
        {
            return CustomFieldValueDAL.dal.GetCustomFieldValueModel(m => m.ID == id);
        }

        public static List<CustomFieldValueModel> GetCustomFieldValueModels(Expression<Func<CustomFieldValueModel, bool>> expression)
        {
            return CustomFieldValueDAL.dal.GetCustomFieldValueModels(expression);
        }

        public static bool InsertCustomFieldValueModel(CustomFieldValueModel entity)
        {
            return CustomFieldValueDAL.dal.InsertCustomFieldValueModel(entity);
        }

        public static bool InsertCustomFieldValueModel(List<CustomFieldValueModel> entities)
        {
            return CustomFieldValueDAL.dal.InsertCustomFieldValueModel(entities);
        }

        public static bool UpdateCustomFieldValueModel(CustomFieldValueModel entity)
        {
            return CustomFieldValueDAL.dal.UpdateCustomFieldValueModel(entity);
        }

        public static bool UpdateCustomFieldValueModel(Dictionary<Field, object> fields, Expression<Func<CustomFieldValueModel, bool>> expression)
        {
            return CustomFieldValueDAL.dal.UpdateCustomFieldValueModel(fields, expression);
        }
    }
}