//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类CustomField。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class CustomFieldBussiness
    {
        public static bool DeleteCustomField(Expression<Func<CustomFieldModel, bool>> expression)
        {
            return CustomFieldDAL.dal.DeleteCustomField(expression);
        }

        public static bool DeleteCustomField(int id)
        {
            return CustomFieldDAL.dal.DeleteCustomField(m => m.ID == id);
        }

        public static CustomFieldModel GetCustomFieldModel(Expression<Func<CustomFieldModel, bool>> expression)
        {
            return CustomFieldDAL.dal.GetCustomFieldModel(expression);
        }

        public static CustomFieldModel GetCustomFieldModel(int id)
        {
            return CustomFieldDAL.dal.GetCustomFieldModel(m => m.ID == id);
        }

        public static List<CustomFieldModel> GetCustomFieldModels(Expression<Func<CustomFieldModel, bool>> expression)
        {
            return CustomFieldDAL.dal.GetCustomFieldModels(expression);
        }

        public static bool InsertCustomFieldModel(CustomFieldModel entity)
        {
            return CustomFieldDAL.dal.InsertCustomFieldModel(entity);
        }

        public static bool InsertCustomFieldModel(List<CustomFieldModel> entities)
        {
            return CustomFieldDAL.dal.InsertCustomFieldModel(entities);
        }

        public static bool UpdateCustomFieldModel(CustomFieldModel entity)
        {
            return CustomFieldDAL.dal.UpdateCustomFieldModel(entity);
        }

        public static bool UpdateCustomFieldModel(Dictionary<Field, object> fields, Expression<Func<CustomFieldModel, bool>> expression)
        {
            return CustomFieldDAL.dal.UpdateCustomFieldModel(fields, expression);
        }

        public static List<CustomFieldModel> GetustomFieldValueBySignIn(int activeid, int infoid)
        {
            return CustomFieldDAL.dal.GetustomFieldValueBySignIn(activeid, infoid);

        }

    }
}