//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using LeoTools.Extension;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类SignInRecord。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class SignInRecordBussiness
    {
        public static bool DeleteSignInRecord(Expression<Func<SignInRecordModel, bool>> expression)
        {
            return SignInRecordDAL.dal.DeleteSignInRecord(expression);
        }

        public static bool DeleteSignInRecord(int id)
        {
            return SignInRecordDAL.dal.DeleteSignInRecord(m => m.ID == id);
        }

        public static SignInRecordModel GetSignInRecordModel(Expression<Func<SignInRecordModel, bool>> expression)
        {
            return SignInRecordDAL.dal.GetSignInRecordModel(expression);
        }

        public static SignInRecordModel GetSignInRecordModel(int id)
        {
            return SignInRecordDAL.dal.GetSignInRecordModel(m => m.ID == id);
        }

        public static List<SignInRecordModel> GetSignInRecordModels(Expression<Func<SignInRecordModel, bool>> expression)
        {
            return SignInRecordDAL.dal.GetSignInRecordModels(expression);
        }

        public static List<SignInRecordModel> GetSignInRecordByUser(int activeid, int userid)
        {
            return SignInRecordDAL.dal.GetSignInRecordByUser(activeid, userid);
        }

        public static List<SignInRecordModel> GetSignInRecordsByActiveID(int ActiveID, int type, PageFliter pageFliter)
        {
            return SignInRecordDAL.dal.GetSignInRecordsByActiveID(ActiveID, type, pageFliter);
        }

        public static bool InsertSignInRecordModel(SignInRecordModel entity)
        {
            return SignInRecordDAL.dal.InsertSignInRecordModel(entity);
        }

        public static bool InsertSignInRecordModel(List<SignInRecordModel> entities)
        {
            return SignInRecordDAL.dal.InsertSignInRecordModel(entities);
        }

        public static bool UpdateSignInRecordModel(SignInRecordModel entity)
        {
            return SignInRecordDAL.dal.UpdateSignInRecordModel(entity);
        }

        public static bool UpdateSignInRecordModel(Dictionary<Field, object> fields, Expression<Func<SignInRecordModel, bool>> expression)
        {
            return SignInRecordDAL.dal.UpdateSignInRecordModel(fields, expression);
        }

        public static bool InserSignInRecordByTran(ActivesModel model, SignInRecordModel signInRecordModel, List<CustomFieldValueModel> values)
        {
            return SignInRecordDAL.dal.InserSignInRecordByTran(model, signInRecordModel, values);
        }

        public static bool UpdateSignInRecordByTran(List<CustomFieldValueModel> values, int infoid)
        {
            return SignInRecordDAL.dal.UpdateSignInRecordByTran(values, infoid);
        }

        public static bool ExitSignIn(int infoid)
        {
            return SignInRecordDAL.dal.ExitSignIn(infoid);
        }

        public static List<SignInRecordModel> GetAllSignInRecord(int eid, PageFliter pageFliter)
        {
            return SignInRecordDAL.dal.GetAllSignInRecord(eid, pageFliter);
        }
    }
}