//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类UserFormID。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class UserFormIDBussiness
    {
        public static bool DeleteUserFormID(Expression<Func<UserFormIDModel, bool>> expression)
        {
            return UserFormIDDAL.dal.DeleteUserFormID(expression);
        }

        public static bool DeleteUserFormID(int id)
        {
            return UserFormIDDAL.dal.DeleteUserFormID(m => m.ID == id);
        }

        public static UserFormIDModel GetUserFormIDModel(Expression<Func<UserFormIDModel, bool>> expression)
        {
            return UserFormIDDAL.dal.GetUserFormIDModel(expression);
        }

        public static UserFormIDModel GetUserFormIDModel(int id)
        {
            return UserFormIDDAL.dal.GetUserFormIDModel(m => m.ID == id);
        }

        public static List<UserFormIDModel> GetUserFormIDModels(Expression<Func<UserFormIDModel, bool>> expression)
        {
            return UserFormIDDAL.dal.GetUserFormIDModels(expression);
        }

        public static bool InsertUserFormIDModel(UserFormIDModel entity)
        {
            return UserFormIDDAL.dal.InsertUserFormIDModel(entity);
        }

        public static bool InsertUserFormIDModel(List<UserFormIDModel> entities)
        {
            return UserFormIDDAL.dal.InsertUserFormIDModel(entities);
        }

        public static bool UpdateUserFormIDModel(UserFormIDModel entity)
        {
            return UserFormIDDAL.dal.UpdateUserFormIDModel(entity);
        }

        public static bool UpdateUserFormIDModel(Dictionary<Field, object> fields, Expression<Func<UserFormIDModel, bool>> expression)
        {
            return UserFormIDDAL.dal.UpdateUserFormIDModel(fields, expression);
        }
    }
}