//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using SignUpTools.DAL;
using SignUpTools.Model;

namespace SignUpTools.Bussiness
{
    /// <summary>
    /// 实体类User。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class UserBussiness
    {
        public static string Login(UserModel model)
        {
            var user = UserDAL.dal.GetUserModel(m => m.OpenID == model.OpenID);
            if (user == null) UserDAL.dal.InsertUserModel(model);
            return model.OpenID;
        }

        public static bool DeleteUser(Expression<Func<UserModel, bool>> expression)
        {
            return UserDAL.dal.DeleteUser(expression);
        }

        public static bool DeleteUser(int id)
        {
            return UserDAL.dal.DeleteUser(m => m.ID == id);
        }

        public static UserModel GetUserModel(Expression<Func<UserModel, bool>> expression)
        {
            return UserDAL.dal.GetUserModel(expression);
        }

        public static UserModel GetUserModel(int id)
        {
            return UserDAL.dal.GetUserModel(m => m.ID == id);
        }

        public static List<UserModel> GetUserModels(Expression<Func<UserModel, bool>> expression)
        {
            return UserDAL.dal.GetUserModels(expression);
        }

        public static bool InsertUserModel(UserModel entity)
        {
            return UserDAL.dal.InsertUserModel(entity);
        }

        public static bool InsertUserModel(List<UserModel> entities)
        {
            return UserDAL.dal.InsertUserModel(entities);
        }

        public static bool UpdateUserModel(UserModel entity)
        {
            return UserDAL.dal.UpdateUserModel(entity);
        }

        public static bool UpdateUserModel(Dictionary<Field, object> fields, Expression<Func<UserModel, bool>> expression)
        {
            return UserDAL.dal.UpdateUserModel(fields, expression);
        }

        public static bool CheckLogin(string token)
        {
            return UserDAL.dal.GetUserModel(m => m.OpenID == token) != null;
            
        }

    }
}