//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Dos.ORM;
using SignUpTools.Model;

namespace SignUpTools.DAL
{
    /// <summary>
    /// 实体类User。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class UserDAL : SqlProvider<UserModel>
    {
        public static UserDAL dal = new UserDAL();
        public bool DeleteUser(Expression<Func<UserModel, bool>> expression)
        {
            return Delete(expression);
        }

        public bool DeleteUser(int id)
        {
            return Delete(m => m.ID == id);
        }

        public UserModel GetUserModel(Expression<Func<UserModel, bool>> expression)
        {
            return GetEntity(expression);
        }

        public UserModel GetUserModel(int id)
        {
            return GetEntity(m => m.ID == id);
        }

        public List<UserModel> GetUserModels(Expression<Func<UserModel, bool>> expression)
        {
            return GetList(expression);
        }

        public bool InsertUserModel(UserModel entity)
        {
            return Insert(entity);
        }

        public bool InsertUserModel(List<UserModel> entities)
        {
            return Insert(entities);
        }

        public bool UpdateUserModel(UserModel entity)
        {
            return Update(entity);
        }

        public bool UpdateUserModel(Dictionary<Field, object> fields, Expression<Func<UserModel, bool>> expression)
        {
            return Update(fields, expression);
        }
    }
}