//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类Actives。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Actives")]
    [Serializable]
    public partial class ActivesModel : Entity
    {
        #region Model
        private int _ID;
        private string _Img;
        private string _Title;
        private string _Content;
        private DateTime? _SigninBeginTIme;
        private DateTime? _SigninEndTime;
        private int? _SignIntMaxCount;
        private int? _SignInCount;
        private decimal? _IsCollectFees;
        private decimal? _CollectFees;
        private int? _IsOpenActiveTime;
        private DateTime? _ActiveBeginTime;
        private DateTime? _ActiveEndTime;
        private string _ActiveAddress;
        private string _ImgDetails;
        private int? _ListShowType;
        private int? _ListReportPermission;
        private int? _IsAllowManyCount;
        private int? _ManyCount;
        private int? _IsAllowCancel;
        private string _PromoterName;
        private string _PromoterMobile;
        private string _PromoterWechat;
        private int? _ReadCount;
        private int? _CreateUserID;
        private DateTime? _CreateTime;
        private int? _can_quit;
        private string _group_qr;
        private int? _is_public;
        private string _latitude;
        private string _longitude;
        private int? _on_behalf_limit;
        private int? _queue;
        private int? _role;
        private int? _user_visible;
        private int? _verify;
        private int? _version;
        private int? _visibility;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 封面图
        /// </summary>
        [Field("Img")]
        public string Img
        {
            get { return _Img; }
            set
            {
                this.OnPropertyValueChange("Img");
                this._Img = value;
            }
        }
        /// <summary>
        /// 标题
        /// </summary>
        [Field("Title")]
        public string Title
        {
            get { return _Title; }
            set
            {
                this.OnPropertyValueChange("Title");
                this._Title = value;
            }
        }
        /// <summary>
        /// 详细信息
        /// </summary>
        [Field("Content")]
        public string Content
        {
            get { return _Content; }
            set
            {
                this.OnPropertyValueChange("Content");
                this._Content = value;
            }
        }
        /// <summary>
        /// 报名开始时间
        /// </summary>
        [Field("SigninBeginTIme")]
        public DateTime? SigninBeginTIme
        {
            get { return _SigninBeginTIme; }
            set
            {
                this.OnPropertyValueChange("SigninBeginTIme");
                this._SigninBeginTIme = value;
            }
        }
        /// <summary>
        /// 报名截止日期
        /// </summary>
        [Field("SigninEndTime")]
        public DateTime? SigninEndTime
        {
            get { return _SigninEndTime; }
            set
            {
                this.OnPropertyValueChange("SigninEndTime");
                this._SigninEndTime = value;
            }
        }
        /// <summary>
        /// 报名人数
        /// </summary>
        [Field("SignIntMaxCount")]
        public int? SignIntMaxCount
        {
            get { return _SignIntMaxCount; }
            set
            {
                this.OnPropertyValueChange("SignIntMaxCount");
                this._SignIntMaxCount = value;
            }
        }
        /// <summary>
        /// 已报名人数
        /// </summary>
        [Field("SignInCount")]
        public int? SignInCount
        {
            get { return _SignInCount; }
            set
            {
                this.OnPropertyValueChange("SignInCount");
                this._SignInCount = value;
            }
        }
        /// <summary>
        /// 是否收费
        /// </summary>
        [Field("IsCollectFees")]
        public decimal? IsCollectFees
        {
            get { return _IsCollectFees; }
            set
            {
                this.OnPropertyValueChange("IsCollectFees");
                this._IsCollectFees = value;
            }
        }
        /// <summary>
        /// 收费金额
        /// </summary>
        [Field("CollectFees")]
        public decimal? CollectFees
        {
            get { return _CollectFees; }
            set
            {
                this.OnPropertyValueChange("CollectFees");
                this._CollectFees = value;
            }
        }
        /// <summary>
        /// 是否开始活动开始/截止日期
        /// </summary>
        [Field("IsOpenActiveTime")]
        public int? IsOpenActiveTime
        {
            get { return _IsOpenActiveTime; }
            set
            {
                this.OnPropertyValueChange("IsOpenActiveTime");
                this._IsOpenActiveTime = value;
            }
        }
        /// <summary>
        /// 活动开始时间
        /// </summary>
        [Field("ActiveBeginTime")]
        public DateTime? ActiveBeginTime
        {
            get { return _ActiveBeginTime; }
            set
            {
                this.OnPropertyValueChange("ActiveBeginTime");
                this._ActiveBeginTime = value;
            }
        }
        /// <summary>
        /// 活动结束时间
        /// </summary>
        [Field("ActiveEndTime")]
        public DateTime? ActiveEndTime
        {
            get { return _ActiveEndTime; }
            set
            {
                this.OnPropertyValueChange("ActiveEndTime");
                this._ActiveEndTime = value;
            }
        }
        /// <summary>
        /// 活动地址
        /// </summary>
        [Field("ActiveAddress")]
        public string ActiveAddress
        {
            get { return _ActiveAddress; }
            set
            {
                this.OnPropertyValueChange("ActiveAddress");
                this._ActiveAddress = value;
            }
        }
        /// <summary>
        /// 图片详情
        /// </summary>
        [Field("ImgDetails")]
        public string ImgDetails
        {
            get { return _ImgDetails; }
            set
            {
                this.OnPropertyValueChange("ImgDetails");
                this._ImgDetails = value;
            }
        }
        /// <summary>
        /// //0什么都不显示 1人数、头像、和昵称 2人数、头像 3人数
        /// </summary>
        [Field("ListShowType")]
        public int? ListShowType
        {
            get { return _ListShowType; }
            set
            {
                this.OnPropertyValueChange("ListShowType");
                this._ListShowType = value;
            }
        }
        /// <summary>
        /// _0.管理员可见1.任何人可见 2.报名参与人可见
        /// </summary>
        [Field("ListReportPermission")]
        public int? ListReportPermission
        {
            get { return _ListReportPermission; }
            set
            {
                this.OnPropertyValueChange("ListReportPermission");
                this._ListReportPermission = value;
            }
        }
        /// <summary>
        /// 是否允许一人多次报名
        /// </summary>
        [Field("IsAllowManyCount")]
        public int? IsAllowManyCount
        {
            get { return _IsAllowManyCount; }
            set
            {
                this.OnPropertyValueChange("IsAllowManyCount");
                this._IsAllowManyCount = value;
            }
        }
        /// <summary>
        /// 代报名人数
        /// </summary>
        [Field("ManyCount")]
        public int? ManyCount
        {
            get { return _ManyCount; }
            set
            {
                this.OnPropertyValueChange("ManyCount");
                this._ManyCount = value;
            }
        }
        /// <summary>
        /// 报名后不允许取消报名
        /// </summary>
        [Field("IsAllowCancel")]
        public int? IsAllowCancel
        {
            get { return _IsAllowCancel; }
            set
            {
                this.OnPropertyValueChange("IsAllowCancel");
                this._IsAllowCancel = value;
            }
        }
        /// <summary>
        /// 发起人名字
        /// </summary>
        [Field("PromoterName")]
        public string PromoterName
        {
            get { return _PromoterName; }
            set
            {
                this.OnPropertyValueChange("PromoterName");
                this._PromoterName = value;
            }
        }
        /// <summary>
        /// 发起人手机号
        /// </summary>
        [Field("PromoterMobile")]
        public string PromoterMobile
        {
            get { return _PromoterMobile; }
            set
            {
                this.OnPropertyValueChange("PromoterMobile");
                this._PromoterMobile = value;
            }
        }
        /// <summary>
        /// 发起人微信号
        /// </summary>
        [Field("PromoterWechat")]
        public string PromoterWechat
        {
            get { return _PromoterWechat; }
            set
            {
                this.OnPropertyValueChange("PromoterWechat");
                this._PromoterWechat = value;
            }
        }
        /// <summary>
        /// 浏览数
        /// </summary>
        [Field("ReadCount")]
        public int? ReadCount
        {
            get { return _ReadCount; }
            set
            {
                this.OnPropertyValueChange("ReadCount");
                this._ReadCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("can_quit")]
        public int? can_quit
        {
            get { return _can_quit; }
            set
            {
                this.OnPropertyValueChange("can_quit");
                this._can_quit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("group_qr")]
        public string group_qr
        {
            get { return _group_qr; }
            set
            {
                this.OnPropertyValueChange("group_qr");
                this._group_qr = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("is_public")]
        public int? is_public
        {
            get { return _is_public; }
            set
            {
                this.OnPropertyValueChange("is_public");
                this._is_public = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("latitude")]
        public string latitude
        {
            get { return _latitude; }
            set
            {
                this.OnPropertyValueChange("latitude");
                this._latitude = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("longitude")]
        public string longitude
        {
            get { return _longitude; }
            set
            {
                this.OnPropertyValueChange("longitude");
                this._longitude = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("on_behalf_limit")]
        public int? on_behalf_limit
        {
            get { return _on_behalf_limit; }
            set
            {
                this.OnPropertyValueChange("on_behalf_limit");
                this._on_behalf_limit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("queue")]
        public int? queue
        {
            get { return _queue; }
            set
            {
                this.OnPropertyValueChange("queue");
                this._queue = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("role")]
        public int? role
        {
            get { return _role; }
            set
            {
                this.OnPropertyValueChange("role");
                this._role = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("user_visible")]
        public int? user_visible
        {
            get { return _user_visible; }
            set
            {
                this.OnPropertyValueChange("user_visible");
                this._user_visible = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("verify")]
        public int? verify
        {
            get { return _verify; }
            set
            {
                this.OnPropertyValueChange("verify");
                this._verify = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("version")]
        public int? version
        {
            get { return _version; }
            set
            {
                this.OnPropertyValueChange("version");
                this._version = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("visibility")]
        public int? visibility
        {
            get { return _visibility; }
            set
            {
                this.OnPropertyValueChange("visibility");
                this._visibility = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.Img,
                _.Title,
                _.Content,
                _.SigninBeginTIme,
                _.SigninEndTime,
                _.SignIntMaxCount,
                _.SignInCount,
                _.IsCollectFees,
                _.CollectFees,
                _.IsOpenActiveTime,
                _.ActiveBeginTime,
                _.ActiveEndTime,
                _.ActiveAddress,
                _.ImgDetails,
                _.ListShowType,
                _.ListReportPermission,
                _.IsAllowManyCount,
                _.ManyCount,
                _.IsAllowCancel,
                _.PromoterName,
                _.PromoterMobile,
                _.PromoterWechat,
                _.ReadCount,
                _.CreateUserID,
                _.CreateTime,
                _.can_quit,
                _.group_qr,
                _.is_public,
                _.latitude,
                _.longitude,
                _.on_behalf_limit,
                _.queue,
                _.role,
                _.user_visible,
                _.verify,
                _.version,
                _.visibility,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._Img,
                this._Title,
                this._Content,
                this._SigninBeginTIme,
                this._SigninEndTime,
                this._SignIntMaxCount,
                this._SignInCount,
                this._IsCollectFees,
                this._CollectFees,
                this._IsOpenActiveTime,
                this._ActiveBeginTime,
                this._ActiveEndTime,
                this._ActiveAddress,
                this._ImgDetails,
                this._ListShowType,
                this._ListReportPermission,
                this._IsAllowManyCount,
                this._ManyCount,
                this._IsAllowCancel,
                this._PromoterName,
                this._PromoterMobile,
                this._PromoterWechat,
                this._ReadCount,
                this._CreateUserID,
                this._CreateTime,
                this._can_quit,
                this._group_qr,
                this._is_public,
                this._latitude,
                this._longitude,
                this._on_behalf_limit,
                this._queue,
                this._role,
                this._user_visible,
                this._verify,
                this._version,
                this._visibility,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Actives");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Actives", "");
            /// <summary>
			/// 封面图
			/// </summary>
			public readonly static Field Img = new Field("Img", "Actives", "封面图");
            /// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "Actives", "标题");
            /// <summary>
			/// 详细信息
			/// </summary>
			public readonly static Field Content = new Field("Content", "Actives", "详细信息");
            /// <summary>
			/// 报名开始时间
			/// </summary>
			public readonly static Field SigninBeginTIme = new Field("SigninBeginTIme", "Actives", "报名开始时间");
            /// <summary>
			/// 报名截止日期
			/// </summary>
			public readonly static Field SigninEndTime = new Field("SigninEndTime", "Actives", "报名截止日期");
            /// <summary>
			/// 报名人数
			/// </summary>
			public readonly static Field SignIntMaxCount = new Field("SignIntMaxCount", "Actives", "报名人数");
            /// <summary>
			/// 已报名人数
			/// </summary>
			public readonly static Field SignInCount = new Field("SignInCount", "Actives", "已报名人数");
            /// <summary>
			/// 是否收费
			/// </summary>
			public readonly static Field IsCollectFees = new Field("IsCollectFees", "Actives", "是否收费");
            /// <summary>
			/// 收费金额
			/// </summary>
			public readonly static Field CollectFees = new Field("CollectFees", "Actives", "收费金额");
            /// <summary>
			/// 是否开始活动开始/截止日期
			/// </summary>
			public readonly static Field IsOpenActiveTime = new Field("IsOpenActiveTime", "Actives", "是否开始活动开始/截止日期");
            /// <summary>
			/// 活动开始时间
			/// </summary>
			public readonly static Field ActiveBeginTime = new Field("ActiveBeginTime", "Actives", "活动开始时间");
            /// <summary>
			/// 活动结束时间
			/// </summary>
			public readonly static Field ActiveEndTime = new Field("ActiveEndTime", "Actives", "活动结束时间");
            /// <summary>
			/// 活动地址
			/// </summary>
			public readonly static Field ActiveAddress = new Field("ActiveAddress", "Actives", "活动地址");
            /// <summary>
			/// 图片详情
			/// </summary>
			public readonly static Field ImgDetails = new Field("ImgDetails", "Actives", "图片详情");
            /// <summary>
			/// //0什么都不显示 1人数、头像、和昵称 2人数、头像 3人数
			/// </summary>
			public readonly static Field ListShowType = new Field("ListShowType", "Actives", "//0什么都不显示 1人数、头像、和昵称 2人数、头像 3人数");
            /// <summary>
			/// _0.管理员可见1.任何人可见 2.报名参与人可见
			/// </summary>
			public readonly static Field ListReportPermission = new Field("ListReportPermission", "Actives", "_0.管理员可见1.任何人可见 2.报名参与人可见");
            /// <summary>
			/// 是否允许一人多次报名
			/// </summary>
			public readonly static Field IsAllowManyCount = new Field("IsAllowManyCount", "Actives", "是否允许一人多次报名");
            /// <summary>
			/// 代报名人数
			/// </summary>
			public readonly static Field ManyCount = new Field("ManyCount", "Actives", "代报名人数");
            /// <summary>
			/// 报名后不允许取消报名
			/// </summary>
			public readonly static Field IsAllowCancel = new Field("IsAllowCancel", "Actives", "报名后不允许取消报名");
            /// <summary>
			/// 发起人名字
			/// </summary>
			public readonly static Field PromoterName = new Field("PromoterName", "Actives", "发起人名字");
            /// <summary>
			/// 发起人手机号
			/// </summary>
			public readonly static Field PromoterMobile = new Field("PromoterMobile", "Actives", "发起人手机号");
            /// <summary>
			/// 发起人微信号
			/// </summary>
			public readonly static Field PromoterWechat = new Field("PromoterWechat", "Actives", "发起人微信号");
            /// <summary>
			/// 浏览数
			/// </summary>
			public readonly static Field ReadCount = new Field("ReadCount", "Actives", "浏览数");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field can_quit = new Field("can_quit", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field group_qr = new Field("group_qr", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field is_public = new Field("is_public", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field latitude = new Field("latitude", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field longitude = new Field("longitude", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field on_behalf_limit = new Field("on_behalf_limit", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field queue = new Field("queue", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field role = new Field("role", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field user_visible = new Field("user_visible", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field verify = new Field("verify", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field version = new Field("version", "Actives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field visibility = new Field("visibility", "Actives", "");
        }
        #endregion
    }
}