//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类ActivesManageApply。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ActivesManageApply")]
    [Serializable]
    public partial class ActivesManageApplyModel : Entity
    {
        #region Model
        private int _ID;
        private DateTime? _ExpirseDate;
        private DateTime? _CreateTime;
        private int? _UseUserID;
        private int? _CreateUserID;
        private string _Code;
        private int? _Status;
        private string _URL;
        private int? _ActiveID;
        private DateTime? _UpdateTime;
        private DateTime? _JoinTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ExpirseDate")]
        public DateTime? ExpirseDate
        {
            get { return _ExpirseDate; }
            set
            {
                this.OnPropertyValueChange("ExpirseDate");
                this._ExpirseDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 同意人的UseID
        /// </summary>
        [Field("UseUserID")]
        public int? UseUserID
        {
            get { return _UseUserID; }
            set
            {
                this.OnPropertyValueChange("UseUserID");
                this._UseUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 验证码
        /// </summary>
        [Field("Code")]
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange("Code");
                this._Code = value;
            }
        }
        /// <summary>
        /// _0 未接受 1.已接收
        /// </summary>
        [Field("Status")]
        public int? Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("URL")]
        public string URL
        {
            get { return _URL; }
            set
            {
                this.OnPropertyValueChange("URL");
                this._URL = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ActiveID")]
        public int? ActiveID
        {
            get { return _ActiveID; }
            set
            {
                this.OnPropertyValueChange("ActiveID");
                this._ActiveID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UpdateTime")]
        public DateTime? UpdateTime
        {
            get { return _UpdateTime; }
            set
            {
                this.OnPropertyValueChange("UpdateTime");
                this._UpdateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("JoinTime")]
        public DateTime? JoinTime
        {
            get { return _JoinTime; }
            set
            {
                this.OnPropertyValueChange("JoinTime");
                this._JoinTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.ExpirseDate,
                _.CreateTime,
                _.UseUserID,
                _.CreateUserID,
                _.Code,
                _.Status,
                _.URL,
                _.ActiveID,
                _.UpdateTime,
                _.JoinTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._ExpirseDate,
                this._CreateTime,
                this._UseUserID,
                this._CreateUserID,
                this._Code,
                this._Status,
                this._URL,
                this._ActiveID,
                this._UpdateTime,
                this._JoinTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "ActivesManageApply");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "ActivesManageApply", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ExpirseDate = new Field("ExpirseDate", "ActivesManageApply", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "ActivesManageApply", "");
            /// <summary>
			/// 同意人的UseID
			/// </summary>
			public readonly static Field UseUserID = new Field("UseUserID", "ActivesManageApply", "同意人的UseID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "ActivesManageApply", "");
            /// <summary>
			/// 验证码
			/// </summary>
			public readonly static Field Code = new Field("Code", "ActivesManageApply", "验证码");
            /// <summary>
			/// _0 未接受 1.已接收
			/// </summary>
			public readonly static Field Status = new Field("Status", "ActivesManageApply", "_0 未接受 1.已接收");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field URL = new Field("URL", "ActivesManageApply", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActiveID = new Field("ActiveID", "ActivesManageApply", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "ActivesManageApply", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field JoinTime = new Field("JoinTime", "ActivesManageApply", "");
        }
        #endregion
    }
}