//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类AuditLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("AuditLog")]
    [Serializable]
    public partial class AuditLogModel : Entity
    {
        #region Model
        private int _ID;
        private string _remark;
        private DateTime? _CreateTime;
        private int? _CreateUserID;
        private int? _SignInRecordID;
        private int? _Status;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("remark")]
        public string remark
        {
            get { return _remark; }
            set
            {
                this.OnPropertyValueChange("remark");
                this._remark = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SignInRecordID")]
        public int? SignInRecordID
        {
            get { return _SignInRecordID; }
            set
            {
                this.OnPropertyValueChange("SignInRecordID");
                this._SignInRecordID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Status")]
        public int? Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.remark,
                _.CreateTime,
                _.CreateUserID,
                _.SignInRecordID,
                _.Status,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._remark,
                this._CreateTime,
                this._CreateUserID,
                this._SignInRecordID,
                this._Status,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "AuditLog");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "AuditLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark", "AuditLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "AuditLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "AuditLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SignInRecordID = new Field("SignInRecordID", "AuditLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "AuditLog", "");
        }
        #endregion
    }
}