//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类CustomFieldValue。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("CustomFieldValue")]
    [Serializable]
    public partial class CustomFieldValueModel : Entity
    {
        #region Model
        private int _ID;
        private int? _ActiveID;
        private int? _SignInID;
        private int? _Type;
        private string _Value;
        private int? _CreateUserID;
        private DateTime? _CreateTime;
        private int? _CustomFieldID;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ActiveID")]
        public int? ActiveID
        {
            get { return _ActiveID; }
            set
            {
                this.OnPropertyValueChange("ActiveID");
                this._ActiveID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SignInID")]
        public int? SignInID
        {
            get { return _SignInID; }
            set
            {
                this.OnPropertyValueChange("SignInID");
                this._SignInID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Type")]
        public int? Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Value")]
        public string Value
        {
            get { return _Value; }
            set
            {
                this.OnPropertyValueChange("Value");
                this._Value = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CustomFieldID")]
        public int? CustomFieldID
        {
            get { return _CustomFieldID; }
            set
            {
                this.OnPropertyValueChange("CustomFieldID");
                this._CustomFieldID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.ActiveID,
                _.SignInID,
                _.Type,
                _.Value,
                _.CreateUserID,
                _.CreateTime,
                _.CustomFieldID,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._ActiveID,
                this._SignInID,
                this._Type,
                this._Value,
                this._CreateUserID,
                this._CreateTime,
                this._CustomFieldID,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "CustomFieldValue");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActiveID = new Field("ActiveID", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SignInID = new Field("SignInID", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Value = new Field("Value", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "CustomFieldValue", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomFieldID = new Field("CustomFieldID", "CustomFieldValue", "");
        }
        #endregion
    }
}