//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类FavoriteActives。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("FavoriteActives")]
    [Serializable]
    public partial class FavoriteActivesModel : Entity
    {
        #region Model
        private int _ID;
        private int? _CreateUserID;
        private DateTime? _CreateTime;
        private int? _ActivesID;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ActivesID")]
        public int? ActivesID
        {
            get { return _ActivesID; }
            set
            {
                this.OnPropertyValueChange("ActivesID");
                this._ActivesID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.CreateUserID,
                _.CreateTime,
                _.ActivesID,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._CreateUserID,
                this._CreateTime,
                this._ActivesID,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "FavoriteActives");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "FavoriteActives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "FavoriteActives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "FavoriteActives", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActivesID = new Field("ActivesID", "FavoriteActives", "");
        }
        #endregion
    }
}