//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类UserFormID。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("UserFormID")]
    [Serializable]
    public partial class UserFormIDModel : Entity
    {
        #region Model
        private int _ID;
        private string _OpenID;
        private string _FormID;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("OpenID")]
        public string OpenID
        {
            get { return _OpenID; }
            set
            {
                this.OnPropertyValueChange("OpenID");
                this._OpenID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FormID")]
        public string FormID
        {
            get { return _FormID; }
            set
            {
                this.OnPropertyValueChange("FormID");
                this._FormID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.OpenID,
                _.FormID,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._OpenID,
                this._FormID,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "UserFormID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "UserFormID", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OpenID = new Field("OpenID", "UserFormID", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FormID = new Field("FormID", "UserFormID", "");
        }
        #endregion
    }
}