//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SignUpTools.Model
{
    /// <summary>
    /// 实体类SignInRecord。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("SignInRecord")]
    [Serializable]
    public partial class SignInRecordModel : Entity
    {
        #region Model
        private int _ID;
        private int? _CreateUserID;
        private DateTime? _CreateTime;
        private int? _ActiveID;
        private DateTime? _UpdateTime;
        private int? _UpdateUserID;
        private int? _type;
        private int? _Status;
        private string _AuditDesc;
        private int? _IsDel;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateUserID")]
        public int? CreateUserID
        {
            get { return _CreateUserID; }
            set
            {
                this.OnPropertyValueChange("CreateUserID");
                this._CreateUserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreateTime")]
        public DateTime? CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        /// <summary>
        /// 活动ID
        /// </summary>
        [Field("ActiveID")]
        public int? ActiveID
        {
            get { return _ActiveID; }
            set
            {
                this.OnPropertyValueChange("ActiveID");
                this._ActiveID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UpdateTime")]
        public DateTime? UpdateTime
        {
            get { return _UpdateTime; }
            set
            {
                this.OnPropertyValueChange("UpdateTime");
                this._UpdateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UpdateUserID")]
        public int? UpdateUserID
        {
            get { return _UpdateUserID; }
            set
            {
                this.OnPropertyValueChange("UpdateUserID");
                this._UpdateUserID = value;
            }
        }
        /// <summary>
        /// _1代报名
        /// </summary>
        [Field("type")]
        public int? type
        {
            get { return _type; }
            set
            {
                this.OnPropertyValueChange("type");
                this._type = value;
            }
        }
        /// <summary>
        /// //1审核 0未审核
        /// </summary>
        [Field("Status")]
        public int? Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AuditDesc")]
        public string AuditDesc
        {
            get { return _AuditDesc; }
            set
            {
                this.OnPropertyValueChange("AuditDesc");
                this._AuditDesc = value;
            }
        }
        /// <summary>
        /// _1删除
        /// </summary>
        [Field("IsDel")]
        public int? IsDel
        {
            get { return _IsDel; }
            set
            {
                this.OnPropertyValueChange("IsDel");
                this._IsDel = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.CreateUserID,
                _.CreateTime,
                _.ActiveID,
                _.UpdateTime,
                _.UpdateUserID,
                _.type,
                _.Status,
                _.AuditDesc,
                _.IsDel,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._CreateUserID,
                this._CreateTime,
                this._ActiveID,
                this._UpdateTime,
                this._UpdateUserID,
                this._type,
                this._Status,
                this._AuditDesc,
                this._IsDel,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "SignInRecord");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "SignInRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID", "SignInRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "SignInRecord", "");
            /// <summary>
			/// 活动ID
			/// </summary>
			public readonly static Field ActiveID = new Field("ActiveID", "SignInRecord", "活动ID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "SignInRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateUserID = new Field("UpdateUserID", "SignInRecord", "");
            /// <summary>
			/// _1代报名
			/// </summary>
			public readonly static Field type = new Field("type", "SignInRecord", "_1代报名");
            /// <summary>
			/// //1审核 0未审核
			/// </summary>
			public readonly static Field Status = new Field("Status", "SignInRecord", "//1审核 0未审核");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditDesc = new Field("AuditDesc", "SignInRecord", "");
            /// <summary>
			/// _1删除
			/// </summary>
			public readonly static Field IsDel = new Field("IsDel", "SignInRecord", "_1删除");
        }
        #endregion
    }

    public partial class SignInRecordModel
    {
        public string CreateUserName { get; set; }
        public string CreateUserAvatars { get; set; }
        public int Num { get; set; }
        public string fieldKeys { get; set; }
        public string fieldNames { get; set; }
        public string fieldVals { get; set; }
        //可以继续扩展table2中的字段
    }
}